name: vietnamhistory_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  go_router:
  cupertino_icons:
    ^1.0.2
    #State Management
  flutter_bloc: ^8.1.3
  get: ^4.6.1
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1

  #DI
  get_it: ^7.6.4
  injectable: ^2.3.0

  #Support UI
  lottie: ^2.7.0
  animated_splash_screen: ^1.3.0
  open_file: ^3.3.2
  uni_links: ^0.5.1
  flutter_zoom_drawer: ^3.1.1
  share_plus: ^7.2.1
  curved_navigation_bar: ^1.0.3
  easy_separator: ^1.0.1
  shimmer: ^3.0.0
  timezone: ^0.9.2
  webview_flutter: ^2.0.13
  flutter_otp_text_field: ^1.1.1
  signalr_netcore: ^1.3.6
  timeago: ^3.6.0
  comment_box: ^0.0.18
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.1
  convex_bottom_bar: ^3.2.0
  bmprogresshud: ^1.0.1
  font_awesome_flutter: ^10.5.0
  after_layout: ^1.2.0
  flutter_lints: ^2.0.0
  responsive_builder: ^0.7.0
  carousel_slider: ^4.2.1
  fluttertoast: ^8.2.2
  animated_custom_dropdown: 1.5.0
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  path_provider: ^2.0.5

  #storage
  shared_preferences: ^2.2.1
  image_picker: ^1.0.4

  jwt_decoder: ^2.0.1

  firebase_crashlytics: ^3.4.4

  #Web
  url_strategy: ^0.2.0

  #Networks
  internet_connection_checker: ^0.0.1+4
  connectivity_plus: ^2.3.5
  retrofit: ^4.0.1
  dio: ^5.3.3
  logger: ^2.0.2+1
  number_pagination: ^0.0.3+2
  flutter_html: 3.0.0-beta.2
  syncfusion_flutter_pdfviewer: ^20.4.54
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/history/
    - assets/images/banner/
    - assets/icons/
    - assets/
