name: vietnamhistory_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
   #State Management
  flutter_bloc: ^8.1.3
  get: ^4.6.1
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1


  #DI
  get_it: ^7.6.4
  injectable: ^2.3.0

  #Support UI
  bmprogresshud: ^1.0.1
  font_awesome_flutter: ^10.5.0
  after_layout: ^1.2.0
  flutter_lints: ^2.0.0
  responsive_builder: ^0.7.0
  carousel_slider: ^4.2.1
  fluttertoast: ^8.2.2
  animated_custom_dropdown: 1.5.0
  cached_network_image: ^3.3.0
  intl: ^0.17.0
  path_provider: ^2.0.5


  #storage
  shared_preferences: ^2.2.1
  image_picker: ^1.0.4


  firebase_crashlytics: ^3.4.4


  #Web
  url_strategy: ^0.2.0



  #Networks
  retrofit: ^4.0.1
  dio: ^5.3.3
  logger: ^2.0.2+1


  flutter_html: ^2.2.1
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0


 

flutter:

  uses-material-design: true


  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/images/history/
    - assets/images/banner/
    - assets/svg/
    - assets/


